version: '3.8'

services:
  web:
    build: .
    container_name: react-app
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge